# Generated by Django 4.1.2 on 2022-10-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.TextField(default='19/10/2022'),
        ),
        migrations.AddField(
            model_name='todo',
            name='finished_date',
            field=models.TextField(default=''),
        ),
    ]
